### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by nilgoyette**
I had to remove the `default-features = false` for nalgebra because there was sudenly a lot of missing stuff. I tried adding the right features instead, to no avail.

As for `quick_error`, I replaced `cause` with `source` and everything's still ok, but I don't actually know what I'm doing ;)

### CODE REVIEW

**Comment by Enet4** [comment]
Hah, you got to this first! ;) Granted, it's easier to find out that some dependencies are outdated now that [deps.rs](https://github.com/deps-rs/deps.rs) has been revived.

> As for `quick_error`, I replaced `cause` with `source` and everything's still ok, but I don't actually know what I'm doing ;)

That is accurate. This version of quick-error seems to be removing its use of deprecated portions of the standard Error API. We were already not using  `description` anymore, and the only thing left was to start using `source` instead of `cause` (also [deprecated in `Error`](https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.cause)).

With nothing else to question here, I can merge right away. Thanks!

**Comment by nilgoyette** [comment]
Sorry to bother you with that, but if you don't have any other merge that you want to do before a while, we would appreciate a release so we can use nalgebra 0.23 in our codebase.

**Comment by nilgoyette** [comment]
Wait, what the hell, I forgot to update `approx` :| Sigh

**Comment by nilgoyette** [comment]
Nevermind, we're better not touch `approx` until the next release of `ndarray`. Sorry for spamming you like that!

**Comment by nilgoyette** [comment]
Hum, you didn't answer my last request with a yes or no so I'll ask again in case you didn't see it.

> Sorry to bother you with that, but if you don't have any other merge that you want to do before a while, we would appreciate a release so we can use nalgebra 0.23 in our codebase.

**Comment by Enet4** [comment]
Right, sorry about that. :x These changes have just been released in 0.11.0.

**Pull request merged**
